pass-gen: add -1 / oneshot mode

diff --git a/pass-gen b/pass-gen
--- a/pass-gen
+++ b/pass-gen
@@ -1,16 +1,10 @@
 #!/bin/sh
 
-if test $# -ne 1
-then
+usage(){
 	echo "Usage: $0 name" >&2
+	echo "Usage: $0 -1 length" >&2
 	exit 2
-fi
-
-if pass git diff | grep . >/dev/null
-then
-	echo >&2 "pass repo in modified state, aborting"
-	exit 1
-fi
+}
 
 cancel(){
 	# cancel exit-code desc
@@ -18,29 +12,62 @@ cancel(){
 	exit $1
 }
 
-name="$1"
-f=/dev/shm/pass-gen.$$.txt
+generate(){
+	if pass git diff | grep . >/dev/null
+	then
+		echo >&2 "pass repo in modified state, aborting"
+		exit 1
+	fi
 
-trap "rm -f '$f'" EXIT
+	name="$1"
+	f=/dev/shm/pass-gen.$$.txt
 
-(
-	pass generate "$name" 20 | tail -1 | sed 's/\x1b\[[^m]*m//g'
-	#    ^~~~~~~~ this may fail, but leave pass with the commit in case
+	trap "rm -f '$f'" EXIT
+
+	(
+		pass generate "$name" 20 | tail -1 | sed 's/\x1b\[[^m]*m//g'
+		#    ^~~~~~~~ this may fail, but leave pass with the commit in case
+		echo
+	) >"$f"
+
+	echo "generated, launching ed..."
+	if ! ed "$f"
+	then
+		q=$?
+		cancel $q "ed aborted"
+	fi
+	if test $(wc -c "$f" | cut -d' ' -f1) -eq 0
+	then cancel 1 "empty password file"
+	fi
+
+	pass git reset --quiet --hard HEAD^
+	pass insert \
+		--multiline \
+		"$name" \
+		< "$f"
+}
+
+oneshot(){
+	LC_ALL=C tr -dc '[:punct:][:alnum:]' </dev/urandom | head -c "$1"
 	echo
-) >"$f"
+}
 
-echo "generated, launching ed..."
-if ! ed "$f"
-then
-	q=$?
-	cancel $q "ed aborted"
-fi
-if test $(wc -c "$f" | cut -d' ' -f1) -eq 0
-then cancel 1 "empty password file"
-fi
+case $# in
+	1)
+		generate "$1"
+		;;
+	2)
+		if test "$1" != -1
+		then usage
+		fi
 
-pass git reset --quiet --hard HEAD^
-pass insert \
-	--multiline \
-	"$name" \
-	< "$f"
+		if ! echo "$2" | grep '^[0-9]\+$' >/dev/null
+		then usage
+		fi
+
+		oneshot "$2"
+		;;
+	*)
+		usage
+		;;
+esac
